In [1]:
#import mysql.connector
from sqlalchemy import create_engine
import pymysql
import numpy as np
import pandas as pd

In [2]:
#pip install openpyxl

In [3]:
#cnx = sqlalchemy.create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')
cnx = create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')

In [4]:
qry="select	clientcode,hiercode,sum(nc) as nc from 	rp_client_preference_hst group by clientcode,hiercode"
df_input=pd.DataFrame(cnx.execute(qry).fetchall())
df_input.columns=['clientcode','hiercode','nc']

In [5]:
df_input.columns=['clientcode','hiercode','nc']

In [6]:
# entire dataframe
df_input

        clientcode hiercode nc
0               10  S523920  1
1               10  S524478  1
2          1000000  S527972  1
3          1000000  S527224  1
4          1000000  S522143  1
...            ...      ... ..
4935154   99999999  S528290  1
4935155   99999999  S500668  3
4935156   99999999  S527079  2
4935157   99999999  S529192  1
4935158   99999999  S530935  1

[4935159 rows x 3 columns]

In [7]:
# client list
qry="select distinct clientcode from rp_client_preference_hst"
client_lst=cnx.execute(qry).fetchall()
lst_client =[ lt[0] for lt in pd.DataFrame.from_dict(client_lst).values.tolist()]
lst_client

['10',
 '1000000',
 '10000071',
 '10000083',
 '10000089',
 '10000101',
 '10000125',
 '10000152',
 '10000199',
 '10000202',
 '10000213',
 '10000227',
 '10000253',
 '10000302',
 '10000305',
 '10000414',
 '10000422',
 '10000441',
 '10000458',
 '10000479',
 '10000660',
 '10000786',
 '10000791',
 '10000794',
 '10000799',
 '10000813',
 '10000832',
 '10000927',
 '10000962',
 '10000992',
 '10001048',
 '10001113',
 '10001196',
 '10001269',
 '10001337',
 '10001364',
 '10001385',
 '10001496',
 '10001497',
 '10001631',
 '10001666',
 '10001684',
 '10001724',
 '10001782',
 '10001811',
 '10001927',
 '10001938',
 '10001943',
 '10002090',
 '10002137',
 '10002180',
 '10002208',
 '10002226',
 '10002270',
 '10002293',
 '10002296',
 '10002346',
 '10002359',
 '10002393',
 '10002396',
 '10002458',
 '10002473',
 '10002596',
 '10002598',
 '10002629',
 '10002652',
 '10002745',
 '10002800',
 '10002802',
 '10002804',
 '10002825',
 '10002841',
 '10002860',
 '10002880',
 '10002899',
 '10002904',
 '10002925',
 '1000293',
 '10002977',
 '10003016',
 '10003028',
 '10003139',
 '10003235',
 '10003251',
 '10003260',
 '10003270',
 '10003279',
 '10003298',
 '10003335',
 '10003338',
 '10003369',
 '10003422',
 '10003449',
 '10003567',
 '10003573',
 '10003650',
 '10003652',
 '10003656',
 '10003663',
 '10003670',
 '10003730',
 '10003742',
 '10003743',
 '10003747',
 '10003753',
 '10003789',
 '10003803',
 '10003824',
 '10003845',
 '10003886',
 '10003926',
 '10003935',
 '10003996',
 '10003998',
 '10004122',
 '10004170',
 '10004213',
 '10004299',
 '10004337',
 '10004345',
 '10004347',
 '10004349',
 '10004380',
 '10004400',
 '10004402',
 '10004442',
 '10004449',
 '10004493',
 '10004523',
 '10004662',
 '10004665',
 '10004670',
 '10004756',
 '10004816',
 '10004827',
 '10004851',
 '10004861',
 '10004910',
 '10004979',
 '10004982',
 '10005005',
 '10005007',
 '10005046',
 '10005069',
 '10005115',
 '10005238',
 '10005249',
 '10005344',
 '10005373',
 '10005449',
 '10005450',
 '10005488',
 '10005501',
 '10005510',
 '10005601',
 '10005613',
 '10005650',
 '10005666',
 '10005734',
 '10005735',
 '10005757',
 '10005759',
 '10005813',
 '10005831',
 '10005839',
 '10005870',
 '10005892',
 '10005905',
 '10005906',
 '10005990',
 '10006008',
 '10006012',
 '10006024',
 '10006093',
 '10006095',
 '10006104',
 '10006144',
 '10006319',
 '10006327',
 '10006452',
 '10006501',
 '10006507',
 '10006513',
 '10006521',
 '10006526',
 '10006543',
 '10006666',
 '10006675',
 '10006741',
 '10006769',
 '10006770',
 '10006794',
 '10006841',
 '10006843',
 '10006864',
 '10006885',
 '10006890',
 '10006926',
 '10006930',
 '10007129',
 '10007152',
 '10007154',
 '10007222',
 '10007225',
 '10007228',
 '10007232',
 '10007247',
 '10007249',
 '10007353',
 '10007396',
 '10007453',
 '10007561',
 '10007563',
 '10007564',
 '10007583',
 '10007597',
 '10007663',
 '10007664',
 '10007674',
 '10007680',
 '10007713',
 '10007767',
 '10007797',
 '10007850',
 '10007856',
 '10007871',
 '10007894',
 '10007916',
 '10007941',
 '10007961',
 '10008038',
 '10008041',
 '10008087',
 '10008106',
 '10008138',
 '10008195',
 '10008196',
 '10008232',
 '10008236',
 '10008264',
 '10008295',
 '10008302',
 '10008331',
 '10008361',
 '10008363',
 '10008381',
 '10008387',
 '10008432',
 '10008448',
 '10008525',
 '10008532',
 '10008556',
 '10008596',
 '10008606',
 '10008724',
 '10008752',
 '10008781',
 '10008800',
 '10008824',
 '10008833',
 '10008862',
 '10008877',
 '10008878',
 '10008901',
 '10008916',
 '10008928',
 '10008977',
 '10009043',
 '10009068',
 '10009153',
 '10009217',
 '10009219',
 '10009263',
 '10009275',
 '10009294',
 '10009308',
 '10009333',
 '10009340',
 '10009349',
 '10009365',
 '10009379',
 '10009380',
 '10009393',
 '10009438',
 '10009446',
 '10009449',
 '10009507',
 '10009556',
 '10009560',
 '10009591',
 '10009641',
 '10009671',
 '10009675',
 '10009717',
 '10009727',
 '10009728',
 '10009772',
 '10009808',
 '10009901',
 '10009913',
 '10009915',
 '10009954',
 '10009974',
 '10009981',
 '10010007',
 '10010013',
 '10010037',
 '10010042',
 '10010085',
 '10010115',
 '10010167',
 '10010168',
 '10010184',
 '10010269',
 '10010341',
 '10010345',
 '10010381',
 '10010468',
 '10010472',
 '10010518',
 '10010558',
 '10010563',
 '10010585',
 '10010619',
 '10010620',
 '10010630',
 '10010681',
 '10010718',
 '10010732',
 '10010784',
 '10010809',
 '10010817',
 '10010833',
 '10010851',
 '10010879',
 '10010901',
 '10010910',
 '10010927',
 '10011002',
 '10011008',
 '10011037',
 '10011046',
 '10011047',
 '10011058',
 '10011071',
 '10011084',
 '10011096',
 '10011202',
 '10011203',
 '10011204',
 '10011207',
 '10011226',
 '10011240',
 '10011278',
 '10011282',
 '10011286',
 '10011355',
 '10011388',
 '10011398',
 '10011418',
 '10011429',
 '10011430',
 '10011480',
 '10011484',
 '10011496',
 '10011504',
 '10011527',
 '10011531',
 '10011541',
 '10011605',
 '10011623',
 '10011715',
 '10011731',
 '10011747',
 '10011794',
 '10011805',
 '10011806',
 '10011835',
 '10011838',
 '10011840',
 '10011866',
 '10011885',
 '10011912',
 '10011917',
 '10011978',
 '10011991',
 '10012025',
 '10012040',
 '10012142',
 '10012218',
 '10012244',
 '10012290',
 '10012304',
 '10012318',
 '10012337',
 '10012363',
 '10012371',
 '10012388',
 '10012390',
 '10012493',
 '10012543',
 '10012563',
 '10012578',
 '10012618',
 '10012633',
 '10012653',
 '10012686',
 '10012687',
 '10012694',
 '10012717',
 '10012732',
 '10012741',
 '10012771',
 '10012775',
 '10012782',
 '10012797',
 '10012800',
 '10012824',
 '10012859',
 '10012933',
 '10012963',
 '10012969',
 '10012971',
 '10012975',
 '10013042',
 '10013056',
 '10013064',
 '10013088',
 '10013107',
 '10013127',
 '10013173',
 '10013220',
 '10013227',
 '10013237',
 '10013303',
 '10013308',
 '10013335',
 '10013342',
 '10013355',
 '10013373',
 '10013398',
 '10013445',
 '10013542',
 '10013579',
 '10013580',
 '10013636',
 '10013691',
 '10013738',
 '10013756',
 '10013790',
 '10013883',
 '10013888',
 '10013890',
 '10013933',
 '10013944',
 '10013949',
 '10014031',
 '10014033',
 '10014040',
 '10014046',
 '10014126',
 '10014138',
 '10014146',
 '10014151',
 '10014344',
 '10014397',
 '10014418',
 '10014420',
 '10014454',
 '10014455',
 '10014475',
 '10014606',
 '10014616',
 '10014642',
 '10014663',
 '10014709',
 '10014724',
 '10014733',
 '10014743',
 '10014745',
 '10014790',
 '10014792',
 '10014794',
 '10014819',
 '10014859',
 '10014917',
 '10014923',
 '10014932',
 '10014973',
 '10014979',
 '10015012',
 '10015020',
 '10015029',
 '10015043',
 '10015094',
 '10015158',
 '10015203',
 '10015240',
 '10015244',
 '10015332',
 '10015354',
 '10015361',
 '10015390',
 '10015419',
 '10015438',
 '10015441',
 '10015450',
 '10015461',
 '10015462',
 '10015530',
 '10015607',
 '10015613',
 '10015774',
 '10015788',
 '10015829',
 '10015848',
 '10015851',
 '10015852',
 '10015889',
 '10015896',
 '10015917',
 '10015952',
 '10015955',
 '10015979',
 '10015983',
 '10016012',
 '10016018',
 '10016022',
 '10016048',
 '10016055',
 '10016125',
 '10016142',
 '10016144',
 '10016146',
 '10016149',
 '10016261',
 '10016263',
 '10016289',
 '10016397',
 '10016398',
 '10016402',
 '10016413',
 '10016421',
 '10016460',
 '10016480',
 '10016482',
 '10016484',
 '10016495',
 '10016543',
 '10016606',
 '10016657',
 '10016668',
 '10016670',
 '10016706',
 '10016719',
 '10016742',
 '10016743',
 '10016779',
 '10016818',
 '10016856',
 '10016937',
 '10016939',
 '10016946',
 '10016966',
 '10016969',
 '10017030',
 '10017054',
 '10017062',
 '10017118',
 '10017133',
 '10017165',
 '10017190',
 '10017198',
 '10017211',
 '10017241',
 '10017256',
 '10017279',
 '10017284',
 '10017308',
 '10017395',
 '10017413',
 '10017458',
 '10017510',
 '10017528',
 '10017592',
 '10017603',
 '10017681',
 '10017696',
 '10017749',
 '10017848',
 '10017869',
 '10017887',
 '10017950',
 '10017951',
 '10017957',
 '10017975',
 '10018012',
 '10018052',
 '10018058',
 '10018085',
 '10018126',
 '10018179',
 '10018263',
 '10018323',
 '10018340',
 '10018356',
 '10018375',
 '10018392',
 '10018395',
 '10018419',
 '10018445',
 '10018466',
 '10018481',
 '10018501',
 '10018538',
 '10018575',
 '10018585',
 '10018675',
 '10018693',
 '10018703',
 '10018706',
 '10018755',
 '10018791',
 '10018820',
 '10018849',
 '10018878',
 '10018891',
 '10018921',
 '10018925',
 '10018930',
 '10018952',
 '10018989',
 '10019067',
 '10019073',
 '10019077',
 '10019080',
 '10019091',
 '10019109',
 '10019125',
 '10019150',
 '10019255',
 '10019279',
 '10019282',
 '10019295',
 '10019299',
 '10019308',
 '10019443',
 '10019549',
 '10019552',
 '10019582',
 '10019587',
 '10019684',
 '10019777',
 '10019902',
 '10019942',
 '10019976',
 '10019978',
 '10019980',
 '10019988',
 '10019989',
 '10019990',
 '10020009',
 '10020040',
 '10020076',
 '10020079',
 '10020129',
 '10020131',
 '10020138',
 '10020166',
 '10020177',
 '10020189',
 '10020199',
 '10020202',
 '10020221',
 '10020222',
 '10020302',
 '10020308',
 '10020355',
 '10020356',
 '10020357',
 '10020358',
 '10020390',
 '10020427',
 '10020472',
 '10020482',
 '10020525',
 '10020577',
 '10020586',
 '10020616',
 '10020687',
 '10020690',
 '10020695',
 '10020730',
 '10020744',
 '10020752',
 '10020753',
 '10020774',
 '10020815',
 '10020828',
 '10020832',
 '10020841',
 '10020879',
 '10020912',
 '10020961',
 '10021058',
 '10021092',
 '10021118',
 '10021172',
 '10021180',
 '10021214',
 '10021298',
 '10021346',
 '10021349',
 '10021397',
 '10021409',
 '10021429',
 '10021482',
 '10021541',
 '10021547',
 '10021579',
 '10021618',
 '10021682',
 '10021713',
 '10021746',
 '10021827',
 '10021867',
 '10021874',
 '10021877',
 '10021905',
 '10021925',
 '10021972',
 '10022017',
 '10022023',
 '10022024',
 '10022029',
 '10022132',
 '10022136',
 '10022157',
 '10022223',
 '10022230',
 '10022271',
 '10022272',
 '10022303',
 '10022305',
 '10022333',
 '10022351',
 '10022477',
 '10022491',
 '10022501',
 '10022505',
 '10022507',
 '10022508',
 '10022659',
 '10022667',
 '10022694',
 '10022700',
 '10022703',
 '10022710',
 '10022741',
 '10022745',
 '10022755',
 '10022787',
 '10022789',
 '10022798',
 '10022804',
 '10022813',
 '10022840',
 '10022884',
 '10022916',
 '10022949',
 '10022964',
 '10023026',
 '10023059',
 '10023077',
 '10023081',
 '10023094',
 '10023107',
 '10023130',
 '10023131',
 '10023157',
 '10023251',
 '10023273',
 '10023302',
 '10023310',
 '10023325',
 '10023394',
 '10023403',
 '10023408',
 '10023410',
 '10023439',
 '10023467',
 '10023477',
 '10023496',
 '10023517',
 '10023530',
 '10023579',
 '10023586',
 '10023588',
 '10023597',
 '10023598',
 '10023610',
 '10023619',
 '10023623',
 '10023649',
 '10023694',
 '10023789',
 '10023815',
 '10023817',
 '10023844',
 '10023865',
 '10023869',
 '10023872',
 '10023873',
 '10023880',
 '10023883',
 '10023889',
 '10023890',
 '10023903',
 '10023915',
 '10023976',
 '10023978',
 '10023981',
 '10023987',
 '10023990',
 '10023996',
 '10024005',
 '10024026',
 '10024031',
 '10024037',
 '10024059',
 '10024062',
 '10024078',
 '10024104',
 '10024111',
 '10024123',
 '10024136',
 '10024138',
 '10024139',
 '10024145',
 '10024151',
 '10024157',
 '10024165',
 '10024172',
 '10024175',
 '10024183',
 '10024187',
 '10024217',
 '10024220',
 '10024231',
 '10024234',
 '10024246',
 '10024247',
 '10024260',
 '10024265',
 '10024269',
 '10024287',
 '10024300',
 '10024306',
 '10024311',
 '10024328',
 '10024332',
 '10024333',
 '10024345',
 '10024348',
 '10024358',
 '10024359',
 '10024360',
 '10024372',
 '10024383',
 '10024387',
 '10024393',
 '10024397',
 '10024398',
 '10024423',
 '10024522',
 '10024525',
 '10024577',
 '10024599',
 '10024600',
 '10024616',
 '10024621',
 '10024628',
 '10024659',
 '10024673',
 '10024694',
 '10024700',
 '10024713',
 '10024717',
 '10024752',
 '10024754',
 '10024829',
 '10024859',
 '10024862',
 '10024896',
 '10024938',
 '10024945',
 '10024949',
 '10024955',
 '10024967',
 '10025061',
 '10025073',
 '10025109',
 '10025119',
 '10025191',
 '1002526',
 '10025265',
 '10025272',
 '10025351',
 '10025373',
 '10025397',
 '10025428',
 '10025557',
 '10025564',
 '10025567',
 '10025612',
 '10025624',
 '10025657',
 '10025667',
 '10025690',
 '10025734',
 '10025782',
 '10025792',
 '10025808',
 '10025811',
 '10025826',
 '10025845',
 '10025914',
 '10025926',
 '10025971',
 '10025987',
 '10026001',
 '10026105',
 '10026107',
 '10026109',
 '10026129',
 '10026153',
 '10026177',
 '10026221',
 '10026232',
 '10026309',
 '10026327',
 '10026377',
 '10026422',
 '10026424',
 '10026445',
 '10026460',
 '10026474',
 '10026509',
 '10026527',
 '10026533',
 '10026615',
 '10026654',
 '10026688',
 '10026697',
 '10026814',
 '10026872',
 '10026882',
 '10026926',
 '10026944',
 '10026954',
 '10026957',
 '10026968',
 '10026969',
 '10026984',
 '10026993',
 '10026997',
 '10027075',
 '10027102',
 '10027108',
 '10027125',
 '10027202',
 '10027220',
 '10027234',
 '10027277',
 '10027278',
 '10027306',
 '10027334',
 '10027366',
 '10027373',
 '10027381',
 '10027389',
 '10027396',
 '10027431',
 '10027452',
 '10027475',
 '10027494',
 '10027524',
 '10027525',
 '10027565',
 '10027601',
 '10027606',
 '10027629',
 '10027630',
 '10027736',
 '10027759',
 '10027815',
 '10027852',
 '10027916',
 '10027994',
 '10028057',
 ...]

In [8]:
list_client_array=np.array(lst_client).reshape((-1,1))

In [9]:
list_client_array

array([['10'],
       ['1000000'],
       ['10000071'],
       ...,
       ['9999960'],
       ['99999992'],
       ['99999999']], dtype='<U8')

In [12]:
print(len(list_client_array))

1022972

In [18]:
# Number of clients to choose randomly
n=20000

In [19]:
# randomly choosing the clients' indexes 
random_array=np.random.choice(len(lst_client),n)

In [22]:
random_array

array([231815, 664578, 655419, ..., 775837, 322784, 899349])

In [23]:
# convering the index array to a list
mask=random_array.tolist()
mask

[231815,
 664578,
 655419,
 316887,
 881887,
 135679,
 616622,
 877293,
 180526,
 338470,
 624257,
 445263,
 951085,
 578264,
 80550,
 982987,
 688511,
 894419,
 972736,
 724852,
 800414,
 855146,
 606742,
 467356,
 385705,
 177134,
 321051,
 898495,
 516133,
 162457,
 786987,
 656193,
 87868,
 439331,
 886547,
 1005525,
 120455,
 688410,
 407960,
 110684,
 741910,
 54163,
 232138,
 876894,
 173758,
 808568,
 599002,
 722624,
 400569,
 978346,
 64833,
 523538,
 311672,
 368897,
 17518,
 221063,
 487821,
 956635,
 984283,
 636574,
 580831,
 825518,
 80721,
 718220,
 766696,
 388970,
 288336,
 732930,
 896741,
 190837,
 144697,
 332854,
 534720,
 367190,
 303500,
 319049,
 360678,
 615663,
 286481,
 291072,
 91245,
 851977,
 447384,
 148998,
 975692,
 77725,
 8942,
 368865,
 298251,
 881431,
 799046,
 930866,
 215444,
 222388,
 115859,
 760409,
 262367,
 480339,
 531423,
 57743,
 923283,
 97857,
 755932,
 867196,
 539261,
 136679,
 1012731,
 216816,
 280295,
 833108,
 88300,
 145831,
 464893,
 248673,
 812606,
 921284,
 252728,
 675164,
 241776,
 77478,
 853028,
 365805,
 115475,
 486057,
 952932,
 99522,
 842730,
 92118,
 574625,
 651153,
 184267,
 551605,
 846382,
 168128,
 279902,
 684098,
 777919,
 955394,
 179716,
 632774,
 252921,
 937126,
 933945,
 303203,
 225366,
 365797,
 320880,
 105963,
 903186,
 95902,
 917511,
 686719,
 949705,
 275377,
 493920,
 956494,
 525261,
 5289,
 565941,
 568178,
 70110,
 356910,
 951750,
 300286,
 885663,
 1018607,
 414422,
 188899,
 262603,
 58916,
 276873,
 494619,
 468808,
 461769,
 498905,
 275264,
 601600,
 727449,
 404611,
 159423,
 855101,
 492521,
 20038,
 279245,
 187200,
 451949,
 671595,
 983356,
 880781,
 367346,
 912182,
 493444,
 369490,
 781807,
 547779,
 645971,
 582041,
 287348,
 869015,
 553156,
 860658,
 1009336,
 47815,
 513510,
 798914,
 585094,
 452484,
 293707,
 285394,
 148005,
 706981,
 284884,
 1013911,
 930148,
 699312,
 564342,
 971223,
 260260,
 384792,
 680561,
 773422,
 490937,
 178765,
 247493,
 113995,
 46860,
 670772,
 217320,
 165238,
 577843,
 586638,
 948368,
 919733,
 397427,
 647149,
 905732,
 374841,
 431632,
 900556,
 32456,
 476487,
 216760,
 1012098,
 377347,
 678831,
 275178,
 71283,
 402767,
 366419,
 668611,
 459272,
 97257,
 476680,
 983484,
 567938,
 460950,
 659556,
 565278,
 763640,
 634185,
 788361,
 297111,
 421871,
 857991,
 534913,
 957707,
 498868,
 777046,
 748793,
 984275,
 138774,
 205132,
 611101,
 474263,
 440578,
 761335,
 580756,
 852364,
 525275,
 657215,
 239764,
 263740,
 108244,
 261491,
 923768,
 768531,
 477323,
 100995,
 70875,
 22120,
 559947,
 486773,
 963487,
 419922,
 197710,
 76432,
 812840,
 492702,
 523666,
 785238,
 769309,
 1001045,
 410222,
 794007,
 600274,
 403564,
 391007,
 132889,
 1013016,
 639534,
 989323,
 460155,
 368647,
 249185,
 954979,
 422364,
 329722,
 98682,
 750377,
 372826,
 919023,
 563387,
 166999,
 515808,
 68375,
 169642,
 416517,
 812464,
 954142,
 459396,
 251606,
 412089,
 626319,
 83393,
 354110,
 819312,
 475082,
 32134,
 221973,
 742778,
 33671,
 547651,
 891904,
 865858,
 333362,
 113976,
 413671,
 607501,
 436152,
 994746,
 716397,
 860660,
 79984,
 639152,
 329386,
 873002,
 985520,
 763420,
 612409,
 384825,
 383675,
 521915,
 324947,
 521625,
 574775,
 413710,
 315414,
 896436,
 145004,
 359794,
 131308,
 227656,
 278205,
 448566,
 360189,
 862077,
 557397,
 433381,
 234025,
 983925,
 435905,
 242102,
 263468,
 887649,
 339362,
 32555,
 95048,
 778315,
 161094,
 670558,
 559378,
 334256,
 995186,
 827831,
 563665,
 626702,
 676576,
 886584,
 45253,
 829712,
 967372,
 200516,
 102302,
 144874,
 542385,
 337061,
 529958,
 481485,
 216843,
 574226,
 686966,
 311144,
 984578,
 174857,
 322026,
 699334,
 118845,
 953078,
 652053,
 592953,
 195873,
 518006,
 245963,
 893838,
 702228,
 150170,
 498411,
 44348,
 424870,
 827393,
 128930,
 172556,
 128709,
 937379,
 428930,
 387180,
 994335,
 882498,
 564546,
 441667,
 13034,
 406355,
 894210,
 615906,
 223363,
 500085,
 31018,
 561210,
 568783,
 514533,
 25,
 58093,
 403482,
 413564,
 407909,
 595239,
 41814,
 390079,
 993194,
 725994,
 225465,
 622396,
 526066,
 193296,
 770996,
 180841,
 596786,
 512815,
 546100,
 517494,
 1021504,
 914642,
 795398,
 277003,
 337411,
 164241,
 192876,
 160133,
 196819,
 334076,
 5799,
 22377,
 1020457,
 34276,
 211261,
 701412,
 1012949,
 478742,
 595136,
 964434,
 833066,
 246961,
 714025,
 391962,
 969746,
 728121,
 462522,
 696759,
 974402,
 758825,
 988062,
 653585,
 837380,
 814577,
 956558,
 446249,
 692624,
 844024,
 28889,
 549948,
 998350,
 316299,
 165092,
 931882,
 899247,
 623981,
 1010199,
 825860,
 633163,
 513499,
 804071,
 613679,
 39342,
 619060,
 44925,
 473529,
 257588,
 928451,
 8149,
 454010,
 532953,
 232750,
 71343,
 672824,
 135510,
 225413,
 574998,
 868759,
 222098,
 283562,
 635294,
 488462,
 922635,
 922862,
 674190,
 35992,
 59601,
 130162,
 715356,
 821594,
 182433,
 708375,
 707831,
 837520,
 653001,
 167750,
 719128,
 553975,
 117958,
 160249,
 309454,
 777715,
 682555,
 635424,
 536952,
 364526,
 544650,
 212749,
 508175,
 910703,
 631578,
 32099,
 266460,
 821875,
 861105,
 464828,
 528937,
 387618,
 290536,
 829973,
 451302,
 833425,
 921431,
 661032,
 713321,
 684006,
 16715,
 293827,
 529731,
 690588,
 356157,
 752233,
 198114,
 964709,
 979825,
 339290,
 941048,
 681450,
 612099,
 762412,
 772605,
 247676,
 608969,
 699794,
 512374,
 207155,
 88903,
 618620,
 802078,
 383009,
 501435,
 255329,
 539967,
 731658,
 984916,
 864616,
 636356,
 830958,
 955327,
 487287,
 157856,
 736494,
 6883,
 339410,
 909113,
 939885,
 80238,
 535623,
 481,
 237012,
 59177,
 852783,
 940736,
 490196,
 840385,
 216188,
 511859,
 319666,
 49048,
 974105,
 1016548,
 44268,
 905350,
 300638,
 238976,
 232129,
 473911,
 845163,
 749819,
 17744,
 132352,
 465795,
 940175,
 823542,
 195197,
 938055,
 354707,
 7078,
 30952,
 1003459,
 762834,
 158635,
 371764,
 383393,
 743753,
 643142,
 357070,
 880680,
 905304,
 497465,
 896779,
 759416,
 222628,
 541716,
 731643,
 788729,
 341522,
 904121,
 377282,
 156221,
 699395,
 751391,
 787901,
 520967,
 701726,
 194484,
 247344,
 176078,
 531994,
 452378,
 962821,
 660467,
 521383,
 264870,
 432698,
 888139,
 898122,
 85890,
 843758,
 1018426,
 103630,
 624748,
 270295,
 94359,
 583310,
 887672,
 931414,
 173631,
 641720,
 136813,
 606538,
 917497,
 987468,
 111176,
 580798,
 47908,
 716235,
 312572,
 955655,
 928340,
 113211,
 229801,
 397678,
 481776,
 627168,
 775779,
 153581,
 856363,
 150664,
 166930,
 639990,
 384953,
 674519,
 516928,
 963487,
 115324,
 515187,
 665782,
 641153,
 215108,
 998371,
 417882,
 612756,
 811801,
 559637,
 876272,
 510220,
 514718,
 345725,
 843537,
 415850,
 746008,
 144861,
 868541,
 354550,
 839057,
 955671,
 252872,
 775526,
 863881,
 332245,
 466555,
 225477,
 637082,
 319967,
 765158,
 578666,
 922275,
 865976,
 727231,
 397530,
 993060,
 491204,
 373089,
 66937,
 9363,
 929910,
 410620,
 405280,
 856139,
 963900,
 529799,
 664246,
 297509,
 480596,
 710846,
 3157,
 545890,
 141941,
 74548,
 988162,
 354880,
 315009,
 138301,
 64058,
 424300,
 377882,
 860993,
 909064,
 775803,
 506257,
 32644,
 194187,
 496786,
 301155,
 676636,
 261607,
 987388,
 626452,
 455141,
 18562,
 805631,
 858235,
 969145,
 744382,
 526413,
 286812,
 652115,
 502351,
 1019356,
 225515,
 920011,
 834316,
 209964,
 956091,
 906746,
 271449,
 844285,
 727332,
 365040,
 399728,
 64948,
 849028,
 407308,
 28544,
 23574,
 98165,
 752342,
 214135,
 69793,
 339830,
 770327,
 295441,
 510978,
 7572,
 763451,
 459572,
 942722,
 659776,
 645751,
 709245,
 183811,
 214598,
 647899,
 851993,
 458171,
 540084,
 149228,
 454647,
 23773,
 235725,
 4156,
 757089,
 840103,
 192599,
 447901,
 630218,
 555850,
 140450,
 308284,
 565895,
 936348,
 45900,
 475094,
 653633,
 433316,
 583891,
 165326,
 1012010,
 141711,
 599002,
 946393,
 75328,
 663760,
 263680,
 515539,
 914767,
 143711,
 807683,
 707804,
 747957,
 272372,
 482349,
 611422,
 250651,
 147240,
 707904,
 513382,
 291576,
 424427,
 646759,
 101637,
 490085,
 483527,
 393002,
 117025,
 641561,
 628004,
 630242,
 611908,
 853988,
 802731,
 637494,
 715671,
 470016,
 221102,
 974058,
 228665,
 218688,
 66206,
 903963,
 550751,
 569058,
 486778,
 806880,
 54892,
 759234,
 127345,
 509439,
 327674,
 524615,
 796600,
 793241,
 261357,
 133752,
 471828,
 375414,
 479222,
 718435,
 192107,
 176888,
 679249,
 715904,
 199295,
 643688,
 553807,
 767481,
 448913,
 929050,
 421161,
 739611,
 865594,
 449798,
 925900,
 807633,
 418550,
 737326,
 108362,
 949770,
 757708,
 117419,
 252954,
 747808,
 829361,
 257449,
 699988,
 879458,
 942489,
 745708,
 635516,
 793552,
 625343,
 839390,
 93450,
 280935,
 166119,
 992871,
 126796,
 519743,
 894533,
 451219,
 27123,
 812391,
 617368,
 643478,
 545825,
 598345,
 93186,
 746320,
 890689,
 761033,
 421496,
 336364,
 799902,
 219469,
 863875,
 544844,
 247611,
 737160,
 381591,
 ...]

In [24]:
list_client_array[247752]

array(['13911384'], dtype='<U8')

In [25]:
# randonly choose clients 
list_client=list_client_array[mask].reshape((1,-1)).tolist()[0]
list_client

['13698686',
 '19842456',
 '19639923',
 '15335424',
 '7255935',
 '12458654',
 '18977082',
 '7167513',
 '13052706',
 '15514301',
 '19099140',
 '16817603',
 '8692364',
 '18458737',
 '11490936',
 '9305271',
 '21091486',
 '7526345',
 '9108515',
 '24006692',
 '5127424',
 '6694643',
 '18838835',
 '17078644',
 '16124412',
 '13026278',
 '15365389',
 '7622433',
 '17681584',
 '12835754',
 '4484542',
 '19657527',
 '11643344',
 '16741736',
 '7363820',
 '9707482',
 '12221483',
 '21077737',
 '16391766',
 '12045292',
 '24851086',
 '10892437',
 '13700819',
 '7156185',
 '12963905',
 '5432869',
 '18723330',
 '23886561',
 '16315564',
 '9211463',
 '11147758',
 '17760041',
 '15217743',
 '15919269',
 '10312181',
 '13564177',
 '17335302',
 '8795723',
 '9339153',
 '19278761',
 '18486953',
 '5978757',
 '11492155',
 '23583460',
 '25790309',
 '16147795',
 '14575950',
 '24406885',
 '7576686',
 '13217081',
 '12574888',
 '15457969',
 '17920073',
 '15893170',
 '15021139',
 '15349417',
 '15799374',
 '18955677',
 '14539125',
 '14629587',
 '11679383',
 '6617536',
 '16862191',
 '12633577',
 '9155836',
 '11457343',
 '10160654',
 '15918933',
 '14739837',
 '7249691',
 '5079131',
 '8294087',
 '13485295',
 '13595547',
 '12139636',
 '25565945',
 '14131753',
 '17252201',
 '17859051',
 '10950563',
 '8116188',
 '11836644',
 '25403994',
 '6982008',
 '17950413',
 '12466702',
 '9837661',
 '13495019',
 '14409143',
 '6190555',
 '11646771',
 '12590432',
 '17051642',
 '13918675',
 '5564219',
 '8073176',
 '13960776',
 '20139473',
 '13856880',
 '11445747',
 '6643711',
 '15871719',
 '12132672',
 '17313891',
 '8720735',
 '11851413',
 '6395613',
 '11712498',
 '18400215',
 '19529686',
 '13079465',
 '18096558',
 '6497343',
 '12882041',
 '14396932',
 '20560687',
 '3581699',
 '8773811',
 '13047103',
 '19222819',
 '13967340',
 '8405208',
 '8342126',
 '15020295',
 '13645590',
 '15871518',
 '15364140',
 '11948097',
 '7701239',
 '11810872',
 '8006946',
 '20838200',
 '8665002',
 '14297003',
 '17403771',
 '8791437',
 '17776230',
 '10091114',
 '18275892',
 '18311361',
 '11267219',
 '15766108',
 '8707976',
 '14901424',
 '7341958',
 '9936806',
 '16449702',
 '13172888',
 '14134901',
 '10967726',
 '14334596',
 '17408186',
 '17090871',
 '17021833',
 '17435963',
 '14294172',
 '18762980',
 '24136077',
 '16368286',
 '12779638',
 '6694279',
 '17385947',
 '10347018',
 '14383213',
 '13119482',
 '16922730',
 '20012469',
 '9314378',
 '7229697',
 '15894318',
 '7897357',
 '17396294',
 '15930340',
 '4094676',
 '18062925',
 '19429022',
 '18502777',
 '14556612',
 '7015099',
 '18118792',
 '6844668',
 '9776594',
 '10790789',
 '17664516',
 '5076706',
 '18532580',
 '16926268',
 '14679208',
 '14515605',
 '12616937',
 '22644668',
 '14504752',
 '9858737',
 '8273976',
 '22151886',
 '18247633',
 '9084627',
 '14113875',
 '16117286',
 '20343482',
 '26122649',
 '17376925',
 '13038428',
 '13909459',
 '12106734',
 '10775893',
 '19991811',
 '13498834',
 '12859966',
 '18451798',
 '18545749',
 '8635942',
 '8044534',
 '16266955',
 '19443828',
 '7757435',
 '15999512',
 '16671481',
 '7663098',
 '10541610',
 '17190840',
 '13494491',
 '9827468',
 '16028284',
 '20261277',
 '14291537',
 '11299584',
 '16354861',
 '15887134',
 '19948896',
 '17007808',
 '11823552',
 '1719481',
 '9317222',
 '18309645',
 '17019400',
 '19708965',
 '18260893',
 '25666747',
 '19233004',
 '4558297',
 '14726596',
 '16558664',
 '6770265',
 '17921189',
 '8820980',
 '17435857',
 '3406239',
 '25130825',
 '9338962',
 '12484018',
 '13381694',
 '18901572',
 '17153561',
 '16749530',
 '25595688',
 '18485312',
 '6624563',
 '17776321',
 '19684053',
 '13832289',
 '14144489',
 '12003260',
 '14124909',
 '8121526',
 '25862022',
 '17211143',
 '11862840',
 '11291227',
 '10374561',
 '18193385',
 '17318241',
 '8943697',
 '16531621',
 '13269820',
 '11406957',
 '5572288',
 '17388404',
 '17762586',
 '4365577',
 '25896607',
 '9630555',
 '16414638',
 '4855899',
 '18739031',
 '16359575',
 '16174035',
 '12420101',
 '9841733',
 '19318398',
 '9418099',
 '17017174',
 '15915721',
 '13922625',
 '8769691',
 '16564958',
 '15437355',
 '11843821',
 '25208901',
 '15966671',
 '8037403',
 '18240677',
 '12874124',
 '17679485',
 '11233467',
 '12892932',
 '16475238',
 '5556071',
 '8748945',
 '17008443',
 '13939718',
 '16429153',
 '19112193',
 '11572692',
 '15719342',
 '5784462',
 '17172033',
 '10536369',
 '13580664',
 '24897561',
 '10562292',
 '18061765',
 '7474232',
 '6958481',
 '15462246',
 '12106391',
 '16438718',
 '18848763',
 '16706554',
 '9504725',
 '23447195',
 '6844808',
 '11486426',
 '19315132',
 '15435329',
 '7072877',
 '9359263',
 '25659742',
 '18919693',
 '16117610',
 '16098478',
 '17736163',
 '15393498',
 '17735419',
 '18403587',
 '16438824',
 '15322275',
 '7573060',
 '12579778',
 '15791264',
 '12395896',
 '13669394',
 '14363298',
 '16875335',
 '15794350',
 '6871062',
 '18171539',
 '16693022',
 '13714552',
 '9329669',
 '16705897',
 '13864462',
 '14142992',
 '7383701',
 '15535088',
 '10543700',
 '11778322',
 '36366920',
 '12810711',
 '19975410',
 '18190923',
 '15468343',
 '9519204',
 '6038392',
 '18243382',
 '19115352',
 '20198474',
 '7364119',
 '10747944',
 '6069406',
 '9002730',
 '13289602',
 '11873059',
 '12576390',
 '18005981',
 '15495407',
 '17840916',
 '17266193',
 '13495266',
 '18394634',
 '20892339',
 '15200475',
 '9347501',
 '12998782',
 '15372186',
 '22152969',
 '12206246',
 '8724094',
 '19551918',
 '18630793',
 '13256547',
 '17702691',
 '13899069',
 '7515622',
 '2238748',
 '12642406',
 '17434592',
 '10736411',
 '16608810',
 '6026751',
 '12333297',
 '12933895',
 '12325996',
 '8408204',
 '16645681',
 '16133700',
 '9497751',
 '7267231',
 '18248936',
 '16770514',
 '10231886',
 '16380085',
 '7520441',
 '18958062',
 '13622442',
 '17440967',
 '10520946',
 '18221199',
 '18315548',
 '17671714',
 '10000813',
 '10956361',
 '16359107',
 '16438419',
 '16391374',
 '18665906',
 '10695272',
 '16163684',
 '9485904',
 '24059313',
 '13645870',
 '19066071',
 '17780729',
 '13237270',
 '25974753',
 '13055407',
 '18676577',
 '17655629',
 '18050713',
 '17699156',
 '9978921',
 '7955006',
 '4905218',
 '14338323',
 '15501392',
 '12852167',
 '13234302',
 '12798673',
 '13262764',
 '15467193',
 '10104185',
 '10379393',
 '9969862',
 '10574872',
 '13456119',
 '22313669',
 '9840883',
 '17233712',
 '18665177',
 '8956578',
 '6189501',
 '13905990',
 '23234947',
 '16190791',
 '9042968',
 '24171156',
 '17026376',
 '21915991',
 '9134771',
 '25507576',
 '9402306',
 '19574204',
 '6286955',
 '5632183',
 '8793520',
 '16839999',
 '21482552',
 '6441101',
 '10482897',
 '18083825',
 '9587735',
 '15331459',
 '12858536',
 '8314378',
 '7630389',
 '19096950',
 '9791333',
 '5992770',
 '19225648',
 '17664431',
 '5264131',
 '18935415',
 '10659515',
 '19019047',
 '10743507',
 '17148032',
 '14091298',
 '8227485',
 '10146841',
 '16940016',
 '17880651',
 '13704841',
 '11301933',
 '20056999',
 '12457097',
 '13645734',
 '18407283',
 '7012888',
 '13584082',
 '14475607',
 '19244772',
 '17339868',
 '8108442',
 '8111766',
 '20111243',
 '10605883',
 '10977305',
 '12364500',
 '23375493',
 '5852482',
 '13066520',
 '22744726',
 '22701425',
 '6288943',
 '19570285',
 '12879671',
 '23654925',
 '18123897',
 '12176339',
 '12800796',
 '15147926',
 '3548267',
 '20449494',
 '19246221',
 '17935165',
 '15841868',
 '18027417',
 '13466224',
 '17590047',
 '7857069',
 '19206214',
 '10536035',
 '14163070',
 '5861662',
 '6858691',
 '17051245',
 '17832081',
 '16134940',
 '14616011',
 '6078133',
 '16918940',
 '6195278',
 '8076639',
 '19735655',
 '23173452',
 '20552837',
 '10299363',
 '14679999',
 '17838925',
 '21275253',
 '15747930',
 '25268374',
 '13272463',
 '8959079',
 '9234566',
 '15534482',
 '8490752',
 '20401427',
 '18918673',
 '25627759',
 '26071723',
 '13910773',
 '18863537',
 '22187695',
 '17646119',
 '13420792',
 '11651533',
 '19005182',
 '5193053',
 '16093963',
 '17475238',
 '14031018',
 '17956806',
 '24348036',
 '9353260',
 '6924334',
 '19276474',
 '6103113',
 '8773293',
 '17325412',
 '12732130',
 '24569942',
 '10123819',
 '15535446',
 '7822622',
 '8462889',
 '11488493',
 '17924556',
 '10014792',
 '13768382',
 '10971855',
 '6636416',
 '8483729',
 '17372025',
 '6364834',
 '13490181',
 '17629131',
 '15355042',
 '10810821',
 '9128992',
 '9902938',
 '10735165',
 '7748224',
 '14907195',
 '13820650',
 '13700766',
 '17150569',
 '6468550',
 '25193507',
 '10315181',
 '12409993',
 '17063568',
 '8469386',
 '5907577',
 '13252065',
 '8424756',
 '15724499',
 '10126959',
 '10519449',
 '9674598',
 '25638975',
 '12762375',
 '15958292',
 '16096556',
 '24942869',
 '19391701',
 '15769294',
 '7226842',
 '7747798',
 '17427282',
 '7577074',
 '25530894',
 '13601687',
 '17988091',
 '24347268',
 '4591285',
 '15563277',
 '7725420',
 '16027998',
 '12691785',
 '22156923',
 '25238336',
 '4532648',
 '17732815',
 '22349045',
 '13245821',
 '13908514',
 '13012997',
 '17867217',
 '16925620',
 '8927538',
 '19729821',
 '17734813',
 '14151379',
 '16682664',
 '7397818',
 '7614867',
 '11625559',
 '6433300',
 '9930698',
 '11885626',
 '19100804',
 '14189629',
 '11754744',
 '18508180',
 '7384098',
 '8310135',
 '12960323',
 '19374949',
 '12467676',
 '18836475',
 '8006824',
 '9391886',
 '12052935',
 '18486089',
 '10792464',
 '23436925',
 '15246729',
 '8776081',
 '8224941',
 '12090881',
 '13684628',
 '16268220',
 '17268031',
 '19126018',
 '3068235',
 '12668509',
 '6721267',
 '12646823',
 '12873508',
 '19322554',
 '16118625',
 '20122103',
 '17691882',
 '8943697',
 '12129419',
 '17675718',
 '19878164',
 '19355119',
 '13482929',
 '9587890',
 '16489523',
 '18925652',
 '5542606',
 '18192064',
 '7139340',
 '17610051',
 '17672886',
 '15621040',
 '6425884',
 '16470905',
 '25027824',
 '12576046',
 '7011057',
 '15722801',
 '6341693',
 '8776206',
 '13964944',
 '2968724',
 '6909388',
 '15453294',
 '17070290',
 '13645903',
 '19282854',
 '15357704',
 '25718963',
 '18462592',
 '8099686',
 '6963332',
 '24123894',
 '16267424',
 '9484375',
 '17379233',
 '15969701',
 '11205389',
 '10168904',
 '8268310',
 '16417631',
 '16372585',
 '6714709',
 '8951267',
 '17839524',
 '19834342',
 '14731077',
 '17254328',
 '22938031',
 '10058581',
 '18049310',
 '12507556',
 '11370512',
 '9403204',
 '15725796',
 '15317296',
 '12480572',
 '11123999',
 '16604773',
 '16031246',
 '6854927',
 '7821022',
 '3073949',
 '17554108',
 '10545068',
 '13243906',
 '17422171',
 '15006738',
 '20199442',
 '14125707',
 '9390329',
 '19113228',
 '16952615',
 '10327310',
 '5319112',
 '6777991',
 '9034035',
 '24969369',
 '17782771',
 '14546590',
 '19554868',
 '17488408',
 '9959446',
 '13646005',
 '8047189',
 '6221022',
 '13446297',
 '8780481',
 '7776744',
 '14199433',
 '6444494',
 '24129905',
 '15845156',
 '16297853',
 '11153817',
 '6559527',
 '16386059',
 '10477234',
 '10395941',
 '11839717',
 '25272440',
 '13476291',
 '11264458',
 '15538672',
 '25944449',
 '14697032',
 '17616331',
 '10135963',
 '25660966',
 '17009332',
 '8519550',
 '19710309',
 '19426648',
 '22801058',
 '13076115',
 '13479483',
 '19453719',
 '6617691',
 '17002554',
 '17957706',
 '12635579',
 '16944831',
 '10398018',
 '13748598',
 '10071892',
 '25444810',
 '6361723',
 '13232612',
 '16869358',
 '19184262',
 '18153031',
 '12496091',
 '15113728',
 '18275650',
 '8393563',
 '10759818',
 '17172205',
 '19578169',
 '16692692',
 '18513978',
 '12860700',
 '9824447',
 '12505523',
 '18723330',
 '8585165',
 '11390351',
 '19822546',
 '14144177',
 '17677803',
 '7959329',
 '12547020',
 '5397308',
 '22699568',
 '25092219',
 '14224125',
 '17271501',
 '18907218',
 '13932505',
 '12614487',
 '22708877',
 '17663640',
 '1464264',
 '16605890',
 '19441102',
 '11867746',
 '17370274',
 '17283519',
 '16205000',
 '12162559',
 '19364975',
 '19144413',
 '19184451',
 '18916390',
 '6667041',
 '5205472',
 '19287377',
 '23399248',
 '17102566',
 '13564458',
 '9128568',
 '13675779',
 '13530214',
 '11189348',
 '7720879',
 '18091220',
 '18324772',
 '17318270',
 '5370038',
 '10905390',
 '25524865',
 '12287092',
 '17602342',
 '15421508',
 '17769596',
 '4972194',
 '4819555',
 '14123829',
 '12440307',
 '17121805',
 '16009112',
 '17242733',
 '23602096',
 '13221291',
 '13019832',
 '20280023',
 '23415471',
 '13281001',
 '19397126',
 '18122820',
 '25822284',
 '16878254',
 '8243865',
 '16549762',
 '24756314',
 '6950110',
 '16902568',
 '8163452',
 '5396467',
 '16509020',
 '24616123',
 '12005277',
 '8665707',
 '25466843',
 '12168304',
 '13968992',
 '25088208',
 '6065919',
 '14088564',
 '22201398',
 '7204050',
 '8516555',
 '25017226',
 '19247423',
 '4836918',
 '19102401',
 '6345939',
 '11741551',
 '14421513',
 '12866357',
 '9482541',
 '12281515',
 '17724563',
 '7530247',
 '16918470',
 '10452160',
 '5553185',
 '18992217',
 '19396527',
 '18048968',
 '18702112',
 '11739049',
 '25038703',
 '7441620',
 '25585301',
 '16555880',
 '15482979',
 '5111550',
 '13547891',
 '6909047',
 '18030926',
 '13910248',
 '24607937',
 '16083646',
 ...]

In [27]:
# convert the listo to a dataframe
client_df=pd.DataFrame(list_client)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)
client_df

      clientcode
450     10000813
17451   10003449
7155    10003996
7026    10005870
1098    10006513
...          ...
15821    9993502
15319    9993707
6575     9994414
4103     9994540
11997    9999523

[20000 rows x 1 columns]

In [28]:
# describing the dataframe
client_df.describe()

       clientcode
count       20000
unique      19812
top      25455091
freq            3

In [46]:
nr_client=len(list_client)

In [47]:
# dataframe filtered by randomly choosing clients
df_input=df_input[df_input['clientcode'].isin(list_client)]
df_input

        clientcode hiercode nc
97        10000813  S529856  2
439       10003449  S522112  1
440       10003449  S526868  4
552       10003996  S521991  2
553       10003996  S529796  1
...            ...      ... ..
4934304    9999523  S523898  1
4934305    9999523  S530839  2
4934306    9999523  S522495  1
4934307    9999523  S522498  1
4934308    9999523  S523968  1

[96778 rows x 3 columns]

In [48]:
df_input.shape

(96778, 3)

In [49]:
# list of hiercode in df_input
list_hiercode=df_input['hiercode'].tolist()
len(list_hiercode)

96778

In [50]:
# converting list to set to eliminate duplicated and again converting to list
list_set_hiercode=list(set(df_input['hiercode'].tolist()) )
len(list_set_hiercode)

2468

In [51]:
# number of hiecode elements
nr_hiercode=len(list_set_hiercode)

In [52]:
# converting the list to a dataframe
dt_hiercode=pd.DataFrame(list_set_hiercode)

In [76]:
# adding the column name and ordering hiercode in ascending order
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)
dt_hiercode
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode

hiercode
S000003       0
S000011       1
S000016       2
S000031       3
S000032       4
           ...
S531090    2463
S531129    2464
S531139    2465
S531147    2466
S531163    2467
Length: 2468, dtype: int64

In [55]:
# creating a matrix of 0's
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [56]:
matrix.shape

(20000, 2468)

In [58]:
# index for hiercode elements
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode))
dt_hiercode.index

RangeIndex(start=0, stop=2468, step=1)

In [60]:
# build series where the index correspond to the hiercode element
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode

hiercode
S000003       0
S000011       1
S000016       2
S000031       3
S000032       4
           ...
S531090    2463
S531129    2464
S531139    2465
S531147    2466
S531163    2467
Length: 2468, dtype: int64

In [74]:
# index for clients
client_df.index = pd.RangeIndex(len(client_df))
client_df.index
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client

clientcode
10000813        0
10003449        1
10003996        2
10005870        3
10006513        4
            ...
9993502     19995
9993707     19996
9994414     19997
9994540     19998
9999523     19999
Length: 20000, dtype: int64

In [ ]:
# Choosing an especific clientcode

In [70]:
clientcode='9999523'

In [71]:
# Retrieving the purchases of an specific client 
df_rut=df_input[df_input['clientcode'].isin([clientcode])]
df_rut=df_rut.sort_values(by='hiercode',ascending=True)
df_rut

        clientcode hiercode nc
4934303    9999523  S500623  1
4934306    9999523  S522495  1
4934307    9999523  S522498  1
4934304    9999523  S523898  1
4934308    9999523  S523968  1
4934305    9999523  S530839  2

In [72]:
# retrieving the result to a list
list_df_result=df_rut['nc']
list_df_result

4934303    1
4934306    1
4934307    1
4934304    1
4934308    1
4934305    2
Name: nc, dtype: object

In [68]:
df_rut['clientcode']

4934303    9999523
4934306    9999523
4934307    9999523
4934304    9999523
4934308    9999523
4934305    9999523
Name: clientcode, dtype: object

In [75]:
idx_client_selected=idx_client[df_rut['clientcode']]
idx_client_selected

clientcode
9999523    19999
9999523    19999
9999523    19999
9999523    19999
9999523    19999
9999523    19999
dtype: int64

In [78]:
idx_hiercode_selected=list(idx_hiercode[df_rut['hiercode']])
idx_hiercode_selected

[363, 687, 689, 879, 912, 2367]

In [79]:
idx_client_selected=list(idx_client[df_rut['clientcode']])
idx_client_selected

[19999, 19999, 19999, 19999, 19999, 19999]

In [81]:
matrix[idx_client_selected,idx_hiercode_selected]=list_df_result

In [82]:
matrix[idx_client_selected,idx_hiercode_selected]

array([1., 1., 1., 1., 1., 2.])

In [83]:
list_df_result

4934303    1
4934306    1
4934307    1
4934304    1
4934308    1
4934305    2
Name: nc, dtype: object

In [106]:
list_client_array[mask]

array([['16086400'],
       ['17922391'],
       ['8702224'],
       ...,
       ['17766107'],
       ['4737232'],
       ['7042709']], dtype='<U8')

In [107]:
lit=list_client_array[mask].reshape((1,-1)).tolist()[0]

In [108]:
len(lit)

20000

In [163]:
client_df=pd.DataFrame(lit)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)

In [164]:
client_df.describe()

       clientcode
count       20000
unique      19820
top      15026440
freq            3

In [165]:
type(client_df['clientcode'][0])

str

In [166]:
client_df

      clientcode
14746   10003567
18666   10004493
8297    10004665
11245   10006327
1323    10009379
...          ...
15135    9997674
4173     9998749
1908     9998856
18500    9999236
17130    9999638

[20000 rows x 1 columns]

In [109]:
nr_client=len(lit)

In [110]:
df_input=df_input[df_input['clientcode'].isin(lit)]

In [111]:
df_input.shape

(93747, 3)

In [112]:
list_hiercode=df_input['hiercode'].tolist()

In [113]:
len(list_hiercode)

93747

In [114]:
set_hiercode=set(df_input['hiercode'].tolist()) 
len(set_hiercode)

2502

In [115]:
set_hiercode

{'S529528',
 'S529707',
 'S527955',
 'S528351',
 'S530262',
 'S523685',
 'S528179',
 'S523673',
 'S524493',
 'S521232',
 'S530816',
 'S530380',
 'S000013',
 'S523853',
 'S527279',
 'S523847',
 'S529967',
 'S527291',
 'S523426',
 'S526402',
 'S502816',
 'S502220',
 'S528271',
 'S527077',
 'S530687',
 'S529503',
 'S530291',
 'S521979',
 'S527320',
 'S527697',
 'S527038',
 'S525108',
 'S529196',
 'S524378',
 'S526340',
 'S524323',
 'S528237',
 'S523535',
 'S502836',
 'S500343',
 'S529983',
 'S529824',
 'S500518',
 'S014016',
 'S525682',
 'S500744',
 'S527001',
 'S528164',
 'S530589',
 'S525008',
 'S528339',
 'S521990',
 'S527158',
 'S530152',
 'S530912',
 'S530264',
 'S529484',
 'S525469',
 'S530177',
 'S529438',
 'S001232',
 'S527054',
 'S524988',
 'S000077',
 'S521878',
 'S527222',
 'S524516',
 'S502686',
 'S004066',
 'S527690',
 'S524367',
 'S026001',
 'S525472',
 'S530884',
 'S529427',
 'S025004',
 'S530971',
 'S523874',
 'S502827',
 'S529371',
 'S529184',
 'S527086',
 'S525450',
 'S527212',
 'S502691',
 'S529964',
 'S528438',
 'S527452',
 'S530399',
 'S502704',
 'S527193',
 'S000100',
 'S521332',
 'S527280',
 'S521671',
 'S500748',
 'S530892',
 'S531038',
 'S530120',
 'S018013',
 'S525172',
 'S529400',
 'S528288',
 'S521646',
 'S500018',
 'S009016',
 'S527029',
 'S529999',
 'S521264',
 'S529920',
 'S522066',
 'S527094',
 'S524473',
 'S530703',
 'S001298',
 'S527382',
 'S529977',
 'S528014',
 'S530974',
 'S528022',
 'S522826',
 'S502736',
 'S500623',
 'S529183',
 'S527949',
 'S521912',
 'S528143',
 'S528419',
 'S524995',
 'S000145',
 'S530724',
 'S523928',
 'S527162',
 'S529640',
 'S524986',
 'S524377',
 'S000029',
 'S001030',
 'S523520',
 'S027009',
 'S527282',
 'S521286',
 'S529875',
 'S528355',
 'S527023',
 'S527045',
 'S522519',
 'S529822',
 'S528359',
 'S523873',
 'S529194',
 'S527133',
 'S530973',
 'S003065',
 'S521931',
 'S523960',
 'S528001',
 'S526007',
 'S530913',
 'S005298',
 'S530921',
 'S531017',
 'S526726',
 'S001251',
 'S523563',
 'S527956',
 'S530409',
 'S527144',
 'S526993',
 'S530391',
 'S529648',
 'S527046',
 'S530371',
 'S528354',
 'S527142',
 'S527008',
 'S526894',
 'S523915',
 'S500061',
 'S527087',
 'S000032',
 'S525098',
 'S522489',
 'S529718',
 'S530190',
 'S010005',
 'S527302',
 'S028001',
 'S039006',
 'S002098',
 'S522130',
 'S524486',
 'S523427',
 'S530479',
 'S527124',
 'S528094',
 'S527431',
 'S012005',
 'S523890',
 'S522484',
 'S523578',
 'S002009',
 'S521705',
 'S530433',
 'S521959',
 'S502769',
 'S528338',
 'S529760',
 'S528005',
 'S005065',
 'S530363',
 'S529769',
 'S527157',
 'S527121',
 'S522141',
 'S528159',
 'S528442',
 'S528279',
 'S523783',
 'S527573',
 'S530052',
 'S527246',
 'S523619',
 'S526822',
 'S526779',
 'S530847',
 'S001122',
 'S529437',
 'S502961',
 'S527210',
 'S530855',
 'S529979',
 'S529474',
 'S527180',
 'S521257',
 'S500372',
 'S032008',
 'S527154',
 'S528439',
 'S522128',
 'S524362',
 'S523869',
 'S530820',
 'S503335',
 'S521875',
 'S000275',
 'S502511',
 'S528034',
 'S521262',
 'S530484',
 'S524514',
 'S530818',
 'S521706',
 'S527559',
 'S527068',
 'S528238',
 'S530898',
 'S000135',
 'S529748',
 'S527987',
 'S523645',
 'S070001',
 'S527235',
 'S530993',
 'S522140',
 'S524338',
 'S523703',
 'S530755',
 'S524389',
 'S528291',
 'S523922',
 'S523976',
 'S526791',
 'S502833',
 'S526868',
 'S500344',
 'S527484',
 'S530692',
 'S529835',
 'S530722',
 'S527223',
 'S046005',
 'S529257',
 'S528334',
 'S524990',
 'S531023',
 'S531081',
 'S524390',
 'S530672',
 'S013002',
 'S521850',
 'S527231',
 'S530041',
 'S527173',
 'S529706',
 'S523957',
 'S500159',
 'S528244',
 'S527476',
 'S522502',
 'S527485',
 'S500141',
 'S528968',
 'S000043',
 'S521266',
 'S522495',
 'S527487',
 'S502518',
 'S528035',
 'S523774',
 'S524567',
 'S531127',
 'S521968',
 'S529872',
 'S527429',
 'S524511',
 'S527310',
 'S527293',
 'S012008',
 'S525949',
 'S503007',
 'S002008',
 'S528142',
 'S521967',
 'S000157',
 'S528594',
 'S523612',
 'S524498',
 'S089001',
 'S047002',
 'S530596',
 'S523554',
 'S526827',
 'S530463',
 'S530309',
 'S528304',
 'S522061',
 'S530406',
 'S524496',
 'S530080',
 'S523782',
 'S529881',
 'S527307',
 'S523551',
 'S527263',
 'S521888',
 'S521233',
 'S521610',
 'S529516',
 'S528417',
 'S502212',
 'S530644',
 'S008034',
 'S500152',
 'S528043',
 'S021003',
 'S527349',
 'S530768',
 'S017013',
 'S502236',
 'S530944',
 'S528029',
 'S503104',
 'S091001',
 'S525733',
 'S530475',
 'S528715',
 'S500216',
 'S524993',
 'S528030',
 'S528160',
 'S530867',
 'S527982',
 'S529434',
 'S528013',
 'S521263',
 'S523621',
 'S523729',
 'S527531',
 'S524474',
 'S523975',
 'S527271',
 'S523125',
 'S521851',
 'S527116',
 'S524852',
 'S527449',
 'S528317',
 'S500045',
 'S527301',
 'S002099',
 'S502517',
 'S523727',
 'S523643',
 'S530202',
 'S530658',
 'S528958',
 'S523965',
 'S027001',
 'S523072',
 'S521276',
 'S527288',
 'S002034',
 'S529871',
 'S502286',
 'S524490',
 'S521615',
 'S529991',
 'S528693',
 'S000036',
 'S526876',
 'S529005',
 'S530384',
 'S529978',
 'S530239',
 'S527049',
 'S523677',
 'S530353',
 'S528726',
 'S500762',
 'S529766',
 'S527076',
 'S500120',
 'S521280',
 'S001069',
 'S527105',
 'S527095',
 'S500534',
 'S530834',
 'S527205',
 'S530067',
 'S502696',
 'S000117',
 'S530385',
 'S524317',
 'S529915',
 'S526986',
 'S523404',
 'S522124',
 'S527315',
 'S531147',
 'S524484',
 'S530786',
 'S528147',
 'S524451',
 'S529719',
 'S502730',
 'S522062',
 'S524348',
 'S524943',
 'S527171',
 'S521251',
 'S527096',
 'S523843',
 'S524363',
 'S003098',
 'S527007',
 'S526794',
 'S529394',
 'S523919',
 'S500600',
 'S526809',
 'S521929',
 'S006040',
 'S502841',
 'S530090',
 'S527183',
 'S521226',
 'S530403',
 'S521261',
 'S529003',
 'S529796',
 'S524442',
 'S003023',
 'S523552',
 'S529932',
 'S527742',
 'S528519',
 'S524409',
 'S523625',
 'S528476',
 'S500468',
 'S529946',
 'S038001',
 'S529772',
 'S527576',
 'S529667',
 'S530880',
 'S011005',
 'S002015',
 'S524315',
 'S500564',
 'S001100',
 'S529954',
 'S521848',
 'S527990',
 'S529877',
 'S502873',
 'S523927',
 'S522505',
 'S522127',
 'S013004',
 'S524508',
 'S528086',
 'S528466',
 'S526856',
 'S502802',
 'S043004',
 'S530784',
 'S523414',
 'S523980',
 'S527197',
 'S525619',
 'S003036',
 'S527249',
 'S529761',
 'S527413',
 'S502728',
 'S523784',
 'S528297',
 'S527265',
 'S530375',
 'S005016',
 'S530372',
 'S528850',
 'S528381',
 'S522023',
 'S521267',
 'S016007',
 'S001018',
 'S529698',
 'S528826',
 'S523418',
 'S530850',
 'S521849',
 'S521237',
 'S526778',
 'S530964',
 'S527161',
 'S521278',
 'S528041',
 'S528964',
 'S500370',
 'S530666',
 'S521287',
 'S530416',
 'S002001',
 'S530997',
 'S528151',
 'S527975',
 'S526820',
 'S030005',
 'S500946',
 'S526790',
 'S523576',
 'S500595',
 'S001011',
 'S529730',
 'S001145',
 'S530642',
 'S002003',
 'S530292',
 'S529837',
 'S526994',
 'S524453',
 'S500228',
 'S530778',
 'S527081',
 'S026003',
 'S500305',
 'S526787',
 'S521240',
 'S502689',
 'S527248',
 'S529800',
 'S523968',
 'S527416',
 'S521971',
 'S530439',
 'S005009',
 'S521882',
 'S529513',
 'S526988',
 'S527211',
 'S502786',
 'S530873',
 'S523405',
 'S521930',
 'S527673',
 'S522903',
 'S527175',
 'S529876',
 'S529892',
 'S502839',
 'S522883',
 'S005027',
 'S528336',
 'S527204',
 'S524106',
 'S003028',
 'S040001',
 'S521861',
 'S528283',
 'S001157',
 'S530122',
 'S521978',
 'S525592',
 'S529444',
 'S500358',
 'S522058',
 'S003039',
 'S523893',
 'S000216',
 'S500619',
 'S523775',
 'S502794',
 'S500941',
 'S527143',
 'S521715',
 'S527251',
 'S527195',
 'S529919',
 'S528450',
 'S500618',
 'S522873',
 'S528900',
 'S530469',
 'S526781',
 'S527698',
 'S528441',
 'S529965',
 'S529420',
 'S529697',
 'S530868',
 'S526342',
 'S527570',
 'S528350',
 'S529908',
 'S502699',
 'S523637',
 'S502831',
 'S526922',
 'S522138',
 'S530407',
 'S522875',
 'S525476',
 'S005056',
 'S523747',
 'S528957',
 'S527179',
 'S001042',
 'S008042',
 'S502975',
 'S529421',
 'S530689',
 'S500375',
 'S529836',
 'S529696',
 'S522467',
 'S528161',
 'S000175',
 'S527047',
 'S525426',
 'S524492',
 'S521969',
 'S522871',
 'S500622',
 'S530470',
 'S527036',
 'S527194',
 'S525106',
 'S531041',
 'S530488',
 'S527207',
 'S527276',
 'S531065',
 'S528527',
 'S041008',
 'S528172',
 'S524074',
 'S523553',
 'S013016',
 'S523962',
 'S500297',
 'S002004',
 'S528664',
 'S524458',
 'S522105',
 'S530950',
 'S529199',
 'S530149',
 'S527126',
 'S523914',
 'S524342',
 'S530411',
 'S000146',
 'S523902',
 'S524037',
 'S000046',
 'S523624',
 'S530592',
 'S006056',
 'S524320',
 'S530271',
 'S529002',
 'S521873',
 'S523636',
 'S529811',
 'S523613',
 'S526403',
 'S529704',
 'S528464',
 'S528572',
 'S523901',
 'S524491',
 'S529450',
 'S530839',
 'S528083',
 'S527228',
 'S530089',
 'S042007',
 'S530823',
 'S000031',
 'S529441',
 'S008002',
 'S500044',
 'S524499',
 'S011013',
 'S530334',
 'S527571',
 'S526880',
 'S011017',
 'S530028',
 'S530395',
 'S529750',
 'S001103',
 'S527240',
 'S523702',
 'S042003',
 'S527490',
 'S524457',
 'S527214',
 'S527114',
 'S529975',
 'S528342',
 'S530110',
 'S500169',
 'S527074',
 'S529738',
 'S001053',
 'S001142',
 'S529856',
 'S529651',
 'S528002',
 'S529370',
 'S500752',
 'S530962',
 'S530400',
 'S529201',
 'S521886',
 'S528033',
 'S527021',
 'S528455',
 'S529849',
 'S521904',
 'S525004',
 'S529935',
 'S527225',
 'S530991',
 'S530342',
 'S500046',
 'S525716',
 'S523534',
 'S527209',
 'S004020',
 'S524075',
 'S500162',
 'S528724',
 'S521611',
 'S530883',
 'S527050',
 'S528245',
 'S502716',
 'S530184',
 'S525444',
 'S523870',
 'S521928',
 'S529019',
 'S527243',
 'S528075',
 'S530195',
 'S000286',
 'S019002',
 'S523801',
 'S500005',
 'S530474',
 'S530714',
 'S521859',
 'S527284',
 'S002117',
 'S528021',
 'S523622',
 'S009005',
 'S528052',
 'S524319',
 'S529486',
 'S527316',
 'S527701',
 'S017298',
 'S521680',
 'S523620',
 'S502796',
 'S528458',
 'S525445',
 'S526343',
 'S500220',
 'S530928',
 'S529941',
 'S527091',
 'S502808',
 'S530254',
 'S525456',
 'S503097',
 'S528959',
 'S529460',
 'S523120',
 'S500936',
 'S527043',
 'S527319',
 'S525434',
 'S529404',
 'S527989',
 'S521934',
 'S530485',
 'S524512',
 'S521710',
 'S530075',
 'S529471',
 'S052001',
 'S530381',
 'S530448',
 'S022011',
 'S502840',
 'S043006',
 'S004042',
 'S528687',
 'S527335',
 'S529389',
 'S529402',
 'S523639',
 'S502600',
 'S003011',
 'S524405',
 'S524445',
 'S525442',
 'S025005',
 'S526890',
 'S503065',
 'S524825',
 'S524815',
 'S527285',
 'S003040',
 'S524454',
 'S521870',
 'S014007',
 'S524316',
 'S527556',
 'S502599',
 'S523671',
 'S526399',
 'S526715',
 'S098001',
 'S527164',
 'S528289',
 'S529693',
 'S529692',
 'S523558',
 'S500831',
 'S521981',
 'S002016',
 'S527217',
 'S530999',
 'S525101',
 'S530934',
 'S528287',
 'S503003',
 'S524314',
 'S005002',
 'S522498',
 'S527167',
 'S527093',
 'S523835',
 'S524438',
 'S006008',
 'S524436',
 'S526789',
 'S527172',
 'S528042',
 'S529754',
 'S527308',
 'S530729',
 'S527996',
 'S530941',
 'S500233',
 'S036002',
 'S526985',
 'S524339',
 'S521962',
 'S528606',
 'S524358',
 'S038005',
 'S530343',
 'S528400',
 'S523579',
 'S528825',
 'S527088',
 'S521620',
 'S001002',
 'S527558',
 'S529193',
 'S523906',
 'S530954',
 'S528897',
 'S527132',
 'S524441',
 'S002042',
 'S527048',
 'S523769',
 'S530454',
 'S530473',
 'S530387',
 'S527044',
 'S523912',
 'S527691',
 'S528036',
 'S528862',
 'S527983',
 'S001146',
 'S522135',
 'S521279',
 'S527338',
 'S523728',
 'S523855',
 'S522885',
 'S527218',
 'S524824',
 'S525105',
 'S524433',
 'S528345',
 'S530061',
 'S524104',
 'S529815',
 'S528180',
 'S523903',
 'S500312',
 'S526867',
 'S500232',
 'S525095',
 'S528574',
 'S001252',
 'S039005',
 'S524826',
 'S527130',
 'S529818',
 'S030004',
 'S008040',
 'S523984',
 'S502738',
 'S529834',
 'S527213',
 'S522477',
 'S054004',
 'S530265',
 'S011006',
 'S522093',
 'S523921',
 'S502875',
 'S007022',
 'S521222',
 'S521281',
 'S530772',
 'S523400',
 'S528564',
 'S524437',
 'S524942',
 'S530316',
 'S527145',
 'S521935',
 'S529711',
 'S528290',
 'S028005',
 'S502702',
 'S521260',
 'S528268',
 'S527092',
 'S530613',
 'S529458',
 'S530404',
 'S526995',
 'S529845',
 ...}

In [116]:
len(set_hiercode)

2502

In [117]:
nr_hiercode=len(set_hiercode)

In [118]:
dt_hiercode=pd.DataFrame(list(set_hiercode))

In [167]:
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)

In [80]:
dt_hiercode.to_excel (r'D:\projectos\recomendation\export_dataframe.xlsx', index = False, header=True)

In [131]:
df_input

        clientcode hiercode nc
441       10003567  S526890  1
442       10003567  S527570  1
443       10003567  S523555  1
444       10003567  S530408  1
445       10003567  S011017  1
...            ...      ... ..
4934292    9999236  S525469  1
4934293    9999236  S528924  1
4934294    9999236  S050004  1
4934295    9999236  S501810  3
4934317    9999638  S000065  1

[93747 rows x 3 columns]

In [83]:
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)

In [84]:
matrix.shape

(20000, 2558)

In [168]:
# indice de los hiercode
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode.index))

In [169]:
dt_hiercode.index

RangeIndex(start=0, stop=2502, step=1)

In [170]:
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode

hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ...
S531129    2497
S531139    2498
S531147    2499
S531155    2500
S531163    2501
Length: 2502, dtype: int64

In [171]:
idx_hiercode['S529528']

1992

In [172]:
# indice de los codeclient
client_df.index = pd.RangeIndex(len(client_df.index))

In [173]:
client_df.index

RangeIndex(start=0, stop=20000, step=1)

In [174]:
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client

clientcode
10003567        0
10004493        1
10004665        2
10006327        3
10009379        4
            ...
9997674     19995
9998749     19996
9998856     19997
9999236     19998
9999638     19999
Length: 20000, dtype: int64

In [175]:
idx_client['9999638']

19999

In [176]:
type(idx_client)

pandas.core.series.Series

In [177]:
idx_client

clientcode
10003567        0
10004493        1
10004665        2
10006327        3
10009379        4
            ...
9997674     19995
9998749     19996
9998856     19997
9999236     19998
9999638     19999
Length: 20000, dtype: int64

In [178]:
idx_hiercode

hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ...
S531129    2497
S531139    2498
S531147    2499
S531155    2500
S531163    2501
Length: 2502, dtype: int64

In [179]:
idx_client['10003567']

0

In [180]:
idx_hiercode['S526890']

1235

In [220]:
df_rut=df_input[df_input['clientcode'].isin(['9999236'])]
df_rut=df_rut.sort_values(by='hiercode',ascending=True)

In [221]:
df_rut

        clientcode hiercode  nc
4934270    9999236  S002098   3
4934276    9999236  S003065   2
4934281    9999236  S004065   1
4934294    9999236  S050004   1
4934282    9999236  S500618   1
4934295    9999236  S501810   3
4934265    9999236  S502874   1
4934258    9999236  S521890   3
4934262    9999236  S521891   1
4934288    9999236  S521926   3
4934267    9999236  S522093   1
4934257    9999236  S523749   2
4934268    9999236  S523890   1
4934278    9999236  S523897   1
4934271    9999236  S523898   1
4934263    9999236  S523972   1
4934285    9999236  S524474   5
4934277    9999236  S524482   1
4934256    9999236  S525434   1
4934292    9999236  S525469   1
4934283    9999236  S525592   1
4934286    9999236  S525953   1
4934284    9999236  S526867   1
4934255    9999236  S527034   1
4934266    9999236  S527206   2
4934272    9999236  S527261   2
4934260    9999236  S527975   1
4934293    9999236  S528924   1
4934280    9999236  S529462   1
4934290    9999236  S529832   1
4934259    9999236  S529944   2
4934273    9999236  S530745   4
4934274    9999236  S530835   1
4934269    9999236  S530845  12
4934291    9999236  S530850   1
4934264    9999236  S530874   2
4934289    9999236  S530889   1
4934261    9999236  S530907   2
4934287    9999236  S530942   1
4934279    9999236  S530943   1
4934275    9999236  S530957   2

In [222]:
list_df_result=df_rut['nc']

In [223]:
list_df_result

4934270     3
4934276     2
4934281     1
4934294     1
4934282     1
4934295     3
4934265     1
4934258     3
4934262     1
4934288     3
4934267     1
4934257     2
4934268     1
4934278     1
4934271     1
4934263     1
4934285     5
4934277     1
4934256     1
4934292     1
4934283     1
4934286     1
4934284     1
4934255     1
4934266     2
4934272     2
4934260     1
4934293     1
4934280     1
4934290     1
4934259     2
4934273     4
4934274     1
4934269    12
4934291     1
4934264     2
4934289     1
4934261     2
4934287     1
4934279     1
4934275     2
Name: nc, dtype: object

In [188]:
idx_client[df_rut['clientcode']]

clientcode
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
dtype: int64

In [224]:
idx_hiercode_selected=idx_hiercode[df_rut['hiercode']]

In [225]:
idx_hiercode_selected

hiercode
S002098      75
S003065      94
S004065     105
S050004     264
S500618     373
S501810     400
S502874     491
S521890     630
S521891     631
S521926     638
S522093     683
S523749     851
S523890     901
S523897     906
S523898     907
S523972     943
S524474    1041
S524482    1046
S525434    1132
S525469    1144
S525592    1150
S525953    1167
S526867    1224
S527034    1286
S527206    1413
S527261    1458
S527975    1624
S528924    1878
S529462    1974
S529832    2084
S529944    2139
S530745    2373
S530835    2398
S530845    2404
S530850    2407
S530874    2418
S530889    2423
S530907    2431
S530942    2448
S530943    2449
S530957    2457
dtype: int64

In [190]:
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
i = [[1, 1], [2, 0], [0, 2]]
i

[[1, 1], [2, 0], [0, 2]]

In [194]:
x, y = np.transpose(i)

In [195]:
x

array([1, 2, 0])

In [196]:
y

array([1, 0, 2])

In [197]:
print(type(i))

<class 'list'>

In [226]:
list_idx_hiercode_selected=list(idx_hiercode_selected)

In [232]:
idx_hiercode_selected['S530845']

2404

In [227]:
list_idx_hiercode_selected

[75,
 94,
 105,
 264,
 373,
 400,
 491,
 630,
 631,
 638,
 683,
 851,
 901,
 906,
 907,
 943,
 1041,
 1046,
 1132,
 1144,
 1150,
 1167,
 1224,
 1286,
 1413,
 1458,
 1624,
 1878,
 1974,
 2084,
 2139,
 2373,
 2398,
 2404,
 2407,
 2418,
 2423,
 2431,
 2448,
 2449,
 2457]

In [228]:
idx_client_selected=idx_client[df_rut['clientcode']]

In [229]:
list_idx_client_selected=list(idx_client_selected)
list_idx_client_selected

[19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998]

In [230]:
matrix[list_idx_client_selected,list_idx_hiercode_selected]=list_df_result

In [231]:
matrix[list_idx_client_selected,list_idx_hiercode_selected]

array([ 3.,  2.,  1.,  1.,  1.,  3.,  1.,  3.,  1.,  3.,  1.,  2.,  1.,
        1.,  1.,  1.,  5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,
        1.,  1.,  1.,  1.,  2.,  4.,  1., 12.,  1.,  2.,  1.,  2.,  1.,
        1.,  2.])

In [233]:
matrix[19998,2404]

12.0